DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS posts CASCADE;
DROP TABLE IF EXISTS admins CASCADE;
DROP TABLE IF EXISTS users_temp CASCADE;
DROP TABLE IF EXISTS barcode CASCADE;
DROP TABLE IF EXISTS messages CASCADE;
DROP TABLE IF EXISTS allow CASCADE;